conda-forge/gnuradio-feedstock

- recipe/meta.yaml
> Bump to rebuild against UHD 3.15.0

- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .scripts/run_docker_build.sh
- recipe/0001-cmake-Install-python-wrapper-exe-for-scripts-on-Wind.patch
- recipe/0001-cmake-Shorten-swig-command-line-by-removing-duplicat.patch
- recipe/0002-cmake-Don-t-generate-.pyc-and-.pyo-files.patch
- recipe/bld.bat
- recipe/install_core.bat
- recipe/install_grc.bat
- recipe/install_qtgui.bat
- recipe/install_uhd.bat
- recipe/install_video_sdl.bat
- recipe/install_zeromq.bat
- recipe/menus/menu-gr_filter_design-windows.json
- recipe/menus/menu-grc-windows.json
- recipe/meta.yaml
> Providing exe for python scripts on Windows and install menu items

- recipe/0001-Fix-drag-n-drop-issue-with-quartz-macos-backend.patch
- recipe/0001-Use-an-ImageSurface-rather-than-UI-back-end.patch
- recipe/meta.yaml
These are pulled from reported gnuradio issues:
https://github.com/gnuradio/gnuradio/issues/2726
https://github.com/gnuradio/gnuradio/issues/2727
Checklist
Closes #14
> Add patches that fix/workaround issues with GRC on OSX with Quartz.

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_boost_cpp1.72.0numpy1.16python3.6.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.72.0numpy1.16python3.7.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.72.0numpy1.16python3.8.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.72.0numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.74.0numpy1.16python3.6.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.74.0numpy1.16python3.7.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.74.0numpy1.16python3.8.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.74.0numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_64_boost_cpp1.72.0numpy1.16python3.6.____cpython.yaml
- .ci_support/osx_64_boost_cpp1.72.0numpy1.16python3.7.____cpython.yaml
- .ci_support/osx_64_boost_cpp1.72.0numpy1.16python3.8.____cpython.yaml
- .ci_support/osx_64_boost_cpp1.72.0numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_64_boost_cpp1.74.0numpy1.16python3.6.____cpython.yaml
- .ci_support/osx_64_boost_cpp1.74.0numpy1.16python3.7.____cpython.yaml
- .ci_support/osx_64_boost_cpp1.74.0numpy1.16python3.8.____cpython.yaml
- .ci_support/osx_64_boost_cpp1.74.0numpy1.19python3.9.____cpython.yaml
- README.md
- recipe/0001-blocks-lib-Enable-files-bigger-than-4-GB-on-Win-with.patch
- recipe/meta.yaml
> Add patch to fix large file sources (>4 GB) on Windows

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_numpy1.16python3.6.____cpython.yaml
- .ci_support/linux_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.16python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
- README.md
- recipe/0001-cmake-Install-python-wrapper-exe-for-scripts-on-Wind.patch
- recipe/0002-cmake-Don-t-generate-.pyc-and-.pyo-files.patch
- recipe/0003-Don-t-use-hard-coded-path-constants.patch
- recipe/0004-cmake-Format-numpy-include-path-in-CMake-style-for-c.patch
- recipe/meta.yaml
> Fix prefix replacement in CMake target due to numpy include path

- README.md
- recipe/meta.yaml
Also tweak outputs to improve metadata and hopefully remove duplicate
app entries.
Checklist
> Fix build string for gnuradio-build-deps

- recipe/0012-runtime-ctrlport-cmake-Fix-thrift-dependency-for-OOT.patch
- recipe/meta.yaml
> Add patch to fix thrift dependency for OOTs.

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_numpy1.17python3.9.____cpython.yaml
- .ci_support/linux_64_numpy1.19python3.7.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.17python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.17python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.7.____cpython.yaml
- .drone.yml
- README.md
- recipe/meta.yaml
> (3.8) Don't compile modtool template Python files, fixing gr_modtool

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_numpy1.17python3.7.____cpython.yaml
- .ci_support/linux_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.17python3.7.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.17python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.9.____cpython.yaml
- .drone.yml
- README.md
- recipe/0001-Don-t-use-hard-coded-path-constants.patch
- recipe/0009-cmake-Move-swath-of-add_definitions-to-gnuradio-runt.patch
- recipe/0011-grc-Be-more-informative-when-missing-options-block.patch
- recipe/0013-grc-Remove-global_blocks_path-preference-and-use-pre.patch
- recipe/meta.yaml
> (3.8) Update to v3.8.3.1

- recipe/0012-Default-for-dict-is-just-and-extra-arg-no-default-ke.patch
- recipe/meta.yaml
> Fix typo in previous patch

- recipe/0001-cmake-Install-python-wrapper-exe-for-scripts-on-Wind.patch
- recipe/0002-cmake-Don-t-generate-.pyc-and-.pyo-files.patch
- recipe/0004-grc-Remove-global_blocks_path-preference-and-use-pre.patch
- recipe/meta.yaml
> (rc) Update to 3.10.0.0rc4

- README.md
- recipe/meta.yaml
- recipe/run_grc_test.py
> Run GRC with timeout to test that it can run

- recipe/0001-cmake-Install-python-wrapper-exe-for-scripts-on-Wind.patch
- recipe/0002-cmake-Don-t-generate-.pyc-and-.pyo-files.patch
- recipe/0003-Use-an-ImageSurface-rather-than-UI-back-end.patch
- recipe/0004-grc-Remove-global_blocks_path-preference-and-use-pre.patch
- recipe/0005-fix-pkg-config.patch
- recipe/0006-cmake-runtime-Set-target_compile_features-to-cxx_std.patch
- recipe/0007-filter-python-Drop-unused-args-argument-overriden-by.patch
- recipe/install_core.bat
- recipe/install_core.sh
- recipe/install_qtgui.bat
- recipe/install_qtgui.sh
- recipe/meta.yaml
> Move gr_filter_tool to qtgui package and add its dependencies

- recipe/0001-cmake-Install-python-wrapper-exe-for-scripts-on-Wind.patch
- recipe/0002-cmake-Don-t-generate-.pyc-and-.pyo-files.patch
- recipe/0003-Use-an-ImageSurface-rather-than-UI-back-end.patch
- recipe/0004-grc-Remove-global_blocks_path-preference-and-use-pre.patch
- recipe/0005-filter-python-Drop-unused-args-argument-overriden-by.patch
- recipe/install_core.bat
- recipe/install_core.sh
- recipe/install_qtgui.bat
- recipe/install_qtgui.sh
- recipe/meta.yaml
> (3.9) Move gr_filter_tool to qtgui package and add its dependencies

- .ci_support/linux_64_numpy1.19python3.7.____cpython.yaml
- .ci_support/linux_64_numpy1.19python3.8.____cpython.yaml
- .ci_support/linux_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.7.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.8.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.21python3.10.____cpython.yaml
- .ci_support/migrations/libthrift0160.yaml
- .ci_support/osx_64_numpy1.19python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml
- README.md
- recipe/0003-Use-an-ImageSurface-rather-than-UI-back-end.patch
- recipe/0004-grc-Remove-global_blocks_path-preference-and-use-pre.patch
- recipe/0005-filter-python-Drop-unused-args-argument-overriden-by.patch
- recipe/0006-cmake-runtime-Manually-set-the-pybind11-internal-bui.patch
- recipe/meta.yaml
> (3.9) Update to version 3.9.6.0

- recipe/0001-cmake-Install-python-wrapper-exe-for-scripts-on-Wind.patch
- recipe/0002-cmake-Don-t-generate-.pyc-and-.pyo-files.patch
- recipe/0004-grc-Remove-global_blocks_path-preference-and-use-pre.patch
- recipe/0005-filter-python-Drop-unused-args-argument-overriden-by.patch
- recipe/0006-cmake-runtime-Manually-set-the-pybind11-internal-bui.patch
- recipe/0007-qtgui-Add-missing-deque-include-to-spectrumdisplayfo.patch
- recipe/meta.yaml
> Update to version 3.10.3.0

- recipe/meta.yaml
Checklist
I forgot one dependency definition in my previous PR #152. Sorry about the mess...
> Add alsa-plugins dep also to gnuradio-core output

- .ci_support/osx_64_numpy1.20python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.20python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.20python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- recipe/build.sh
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> Try to enable building for older macOS targets than 10.15

- .ci_support/linux_64_numpy1.20python3.7.____cpython.yaml
- .ci_support/linux_64_numpy1.20python3.8.____cpython.yaml
- .ci_support/linux_64_numpy1.20python3.9.____cpython.yaml
- .ci_support/linux_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.20python3.7.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.20python3.8.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.20python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.20python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.20python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.20python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.21python3.10.____cpython.yaml
- .ci_support/migrations/uhd430.yaml
- .ci_support/osx_64_numpy1.20python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.20python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.20python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.20python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.20python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml
- .ci_support/win_64_numpy1.20python3.7.____cpython.yaml
- .ci_support/win_64_numpy1.20python3.8.____cpython.yaml
- .ci_support/win_64_numpy1.20python3.9.____cpython.yaml
- .ci_support/win_64_numpy1.21python3.10.____cpython.yaml
- recipe/meta.yaml
> Rebuild for uhd 4.3.0

- .ci_support/linux_64_numpy1.20python3.7.____cpython.yaml
- .ci_support/linux_64_numpy1.20python3.8.____cpython.yaml
- .ci_support/linux_64_numpy1.20python3.9.____cpython.yaml
- .ci_support/linux_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.20python3.7.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.20python3.8.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.20python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.20python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.20python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.20python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.21python3.10.____cpython.yaml
- .ci_support/migrations/uhd430.yaml
- .ci_support/osx_64_numpy1.20python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.20python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.20python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.20python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.20python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml
- .ci_support/win_64_numpy1.20python3.7.____cpython.yaml
- .ci_support/win_64_numpy1.20python3.8.____cpython.yaml
- .ci_support/win_64_numpy1.20python3.9.____cpython.yaml
- .ci_support/win_64_numpy1.21python3.10.____cpython.yaml
- recipe/meta.yaml
> (3.9) Rebuild for uhd 4.3.0

- README.md
- recipe/meta.yaml
Checklist
Requested at https://github.com/gnuradio/pmt/issues/69.
> Split gnuradio-pmt into separate package that core depends on

- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
> Enable testing so OOT modules have it by default, but don't run it

- recipe/0007-iio-cmake-revert-libad9361-linkage-back-to-public.patch
- recipe/meta.yaml
> Add upstream patch to re-enable PlutoSDR support

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_numpy1.21python3.8.____cpython.yaml
- .ci_support/linux_64_numpy1.21python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.21python3.8.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.21python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.21python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.21python3.9.____cpython.yaml
- .ci_support/migrations/libthrift0181.yaml
- .ci_support/osx_64_numpy1.21python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.9.____cpython.yaml
- .ci_support/win_64_numpy1.21python3.8.____cpython.yaml
- .ci_support/win_64_numpy1.21python3.9.____cpython.yaml
- README.md
- conda-forge.yml
- recipe/build.sh
- recipe/meta.yaml
> Update to version 3.10.6.0

- recipe/0002-grc-Remove-global_blocks_path-preference-and-use-pre.patch
- recipe/0005-grc-qt-Don-t-error-when-missing-manifests-dir.patch
- recipe/meta.yaml
Checklist
* ~[ ] Reset the build number to `0` (if the version changed)~
> Add qdarkstyle dep for grc (qt) and patches to fix running grc-qt

- recipe/0006-grc-qt-Continue-instead-of-break-for-empty-example-p.patch
- recipe/meta.yaml
Checklist
* ~[ ] Reset the build number to `0` (if the version changed)~
> Add patch to fix grc-qt example browser

- .ci_support/linux_64_python3.10.____cpython.yaml
- .ci_support/linux_64_python3.11.____cpython.yaml
- .ci_support/linux_64_python3.12.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/linux_aarch64_python3.10.____cpython.yaml
- .ci_support/linux_aarch64_python3.11.____cpython.yaml
- .ci_support/linux_aarch64_python3.12.____cpython.yaml
- .ci_support/linux_aarch64_python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_python3.11.____cpython.yaml
- .ci_support/linux_ppc64le_python3.12.____cpython.yaml
- .ci_support/linux_ppc64le_python3.9.____cpython.yaml
- .ci_support/osx_64_python3.10.____cpython.yaml
- .ci_support/osx_64_python3.11.____cpython.yaml
- .ci_support/osx_64_python3.12.____cpython.yaml
- .ci_support/osx_64_python3.9.____cpython.yaml
- .ci_support/osx_arm64_python3.10.____cpython.yaml
- .ci_support/osx_arm64_python3.11.____cpython.yaml
- .ci_support/osx_arm64_python3.12.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- .ci_support/win_64_python3.10.____cpython.yaml
- .ci_support/win_64_python3.11.____cpython.yaml
- .ci_support/win_64_python3.12.____cpython.yaml
- .ci_support/win_64_python3.9.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- conda-forge.yml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
Checklist
* ~[ ] Reset the build number to `0` (if the version changed)~
> Fix overlinking and clean up depdendencies
